### ISSUE TITLE
Resize number of masters

### ISSUE THREAD

**Issue by sesh-kebab** [dcos/terraform-dcos#58]
Is is possible to resize your masters via terraform? It doesn't seem supported right now. Adjusting `num_of_masters` in your tfvar file from a value of `1` -> `3`, the new masters never 2 & 3 never reach a healthy state after a `terraform apply`.

The below never returns.
```
# Watch Master Nodes Start
  provisioner "remote-exec" {
    inline = [
      "until $(curl --output /dev/null --silent --head --fail http://${element(aws_instance.master.*.private_ip, count.index)}/); do printf 'loading DC/OS...'; sleep 10; done",
    ]
  }
```

**Comment by rimusz** [comment]
you must to set masters number before doing terraform apply for the first time, adding masters to currently running dc/os cluster is not supported by dc/os

**Comment by sesh-kebab** [comment]
@rimusz - ok, thanks.
