### ISSUE TITLE
CoreOS and locksmithd/update engine

### ISSUE THREAD

**Issue by dispalt** [dcos/terraform-dcos#59]
So while you've disabled locksmithd, you haven't disable update-engine, which means it will still get updates and if you happen to restart coreos will automatically upgrade it.

I'd recommend something like this:

```
sudo systemctl disable locksmithd
sudo systemctl stop locksmithd
sudo systemctl mask locksmithd

sudo systemctl disable update-engine
sudo systemctl stop update-engine
sudo systemctl mask update-engine
sudo systemctl restart docker # Restarting docker to ensure its ready. Seems like its not during first usage.
```

**Comment by bernadinm** [comment]
Thank you @dispalt! I have deployed this and we're all set to go!
