### ISSUE TITLE
Cannot connect via ssh in gcp using ssh-agent

### ISSUE THREAD

**Issue by genevera** [dcos/terraform-dcos#68]
I keep getting auth errors when the provision script is run:

```
2018-08-24T10:42:32.401-0400 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/08/24 10:42:32 [WARN] retryable error: ssh: handshake failed: ssh: disconnect, reason 2: Too many authentication failures for centos
```

I can ssh into the instances directly using my ssh-agent and the key:
```
➜ ssh centos@<dcos-master-1> -i ~/.ssh/js_hackweek_rsa
Warning: Permanently added '<dcos-master-1>' (ECDSA) to the list of known hosts.
[centos@jenn-tf0983-master-1 ~]$
```

the desired_cluster_profile.tfvars file does include the correct pubkey:
```
gcp_ssh_pub_key_file = "~/.ssh/js_hackweek_rsa.pub"
```
When I add the location of the privkey to the config, it works.

**Comment by bernadinm** [comment]
@genevera, from the same machine that terraform is running from, can you see if the private key is also located in the ssh-agent? You can confirm below by running this command locally. It should look like something like this below.

```bash
$ ssh-add -l
4096 SHA256:i+SOHSa90fhA+H9h23rk+ffCdOk2ZmDWoRIK8aw4 ~/.ssh/js_hackweek_rsa (RSA)
```

**Comment by bernadinm** [comment]
@genevera I will mark this issue as closed. If you feel that this is an still an issue, which the solution I provided should be sufficient, please reopen this request.
