### ISSUE TITLE
Issues with Upgrading 1.9.5 to 1.10.0

### ISSUE THREAD

**Issue by bernadinm** [dcos/terraform-dcos#7]
@dotemacs had pointed out an issue in the DC/OS Community terraform channel that he has difficulty upgrading from 1.9.5 to 1.10.0.

Creating this ticket to track this effort of what the issue is and providing the solution.

**Comment by dotemacs** [comment]
Hello @bernadinm 

your change does fix the issue raised.

Just did a test upgrade from 1.9.5 -> 1.10.0 -> 1.10.1 and it went smoothly.

Thank you for your time & feel free to close this issue.

**Comment by bernadinm** [comment]
thank you @dotemacs for raising this issue! It will now be closed.

Have a great day ahead!
